- name: demo on task level variables
  hosts: localhost
  connection: local # it will not ask for username and password
  vars:
    COURSE: "Ansible"
    TRAINER: "sivakumar"
    DURATION: "150HRS"
  tasks:
  - name: print information
    vars:
      COURSE: "DevSecOps with AIOps"
    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"