- name: demo on inventory variables
  hosts: frontend
  #connection: local
  tasks:
  - name: print information
    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}, common_key: {{ common_key }}"