- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    debug:
      msg: "Hi {{ item }}" # item is reserved special variable
    loop:
    - Ramesh
    - Raheem
    - John