[frontend]
172.31.47.72

[catalogue]
172.31.27.249


[user]
172.31.27.250

[cart]
172.31.27.251

; group of groups
[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

local group vars
[local:vars]
COURSE="Ansible"
TRAINER="Sivakumar"
DURATION="10HRS"

